sudo: required
language: generic 
services: 
  - docker

before_install:
  - docker build -t antolc/multi-test -f ./client/Dockerfile.dev .

script:
  - docker run -e CI=true antolc/multi-test npm run test

after_success:
  - docker build -t antolc/multi-client -f ./client .
  - docker build -t antolc/multi-server -f ./server .
  - docker build -t antolc/multi-nginx  -f ./nginx .
  - docker build -t antolc/multi-worker -f ./worker .
  # LOGIN TO Docker CLI
  - echo "$DOCKER_PASS" | docker login -u "$DOCKER_ID" -- password--stdin
  # Take those images and push them to docker hub
  - docker push antolc/multi-client
  - docker push antolc/multi-server
  - docker push antolc/multi-nginx
  - docker push antolc/multi-worker